-- 코드를 입력하세요
SELECT C.CAR_ID, ROUND(AVG(C.DURATION), 1) AS AVERAGE_DURATION FROM 
(SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS C
GROUP BY C.CAR_ID HAVING ROUND(AVG(C.DURATION), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;