-- 코드를 작성해주세요
# SELECT FISH_COUNT, FISH_NAME FROM FISH_NAME_INFO
# WHERE FISH_COUNT IN (SELECT COUNT(ID) FROM FISH_INFO GROUP BY FISH_TYPE);

# SELECT COUNT(ID) FROM FISH_INFO GROUP BY FISH_TYPE;

SELECT COUNT(ID) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME FROM FISH_INFO
LEFT JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_NAME
ORDER BY FISH_COUNT DESC;