SELECT CAR_ID, 
CASE
    WHEN 
        (CASE 
            WHEN SUM('2022-10-16' BETWEEN START_DATE AND END_DATE) THEN 1
         ELSE 0 END) = 0
    THEN '대여 가능'
    ELSE '대여중'
END
AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;