-- 코드를 작성해주세요
# SELECT ID, FISH_NAME, LENGTH
SELECT ID, FISH_NAME, LENGTH
FROM (SELECT * FROM FISH_INFO WHERE LENGTH IN (SELECT MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE)) F INNER JOIN FISH_NAME_INFO FNI ON F.FISH_TYPE = FNI.FISH_TYPE 
WHERE LENGTH IS NOT NULL
ORDER BY 1;