-- 코드를 작성해주세요
# SELECT SUM(SCORE) AS SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL FROM HR_GRADE
# LEFT JOIN HR_EMPLOYEES
# ON HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
# WHERE HR_GRADE.YEAR = '2022'
# GROUP BY EMP_NO
# ORDER BY 1 DESC
# LIMIT 1;

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL FROM HR_EMPLOYEES E, HR_GRADE G WHERE E.EMP_NO = G.EMP_NO AND G.YEAR = '2022' GROUP BY EMP_NO ORDER BY 1 DESC LIMIT 1;